# Course: GRS-80436 / MSc Thesis
# Project: AHN canopy gap detection
# Author: Niek Koelewijn
# Organisation: Wageningen University
# Supervisor: L.C. Vreugdenhil MSc.
# Year: 2022

### Description ###
# Script to analyse data from the yield tables (Jansen et al., 2018) to determine
# a threshold for the maximum vegetation height in a canopy gap, and to determine
# the maximum possible height increment in 3 years to determine the difference
# between lateral and horizontal gap closure.


## Maximum vegetation height

# Get data for each tree species: beech, oak, scotch pine, japanese larch,
# douglas fir and norway spruce
maxvegdat <- tibble(diameter = c(NA,
              -1.70,
              0.40,
              2.30,
              4.00,
              6.20,
              8.30,
              -3.80,
              -1.20,
              0.80,
              2.40,
              3.50,
              5.10,
              6.90,
              NA,
              -2.90,
              -0.60,
              1.50,
              3.10,
              4.20,
              6.00,
              -3.70,
              -0.50,
              1.90,
              3.70,
              6.20,
              8.50,
              10.70,
              NA,
              -3.10,
              1.10,
              4.10,
              7.70,
              11.50,
              15.20,
              NA,
              -3.30,
              -0.80,
              3.50,
              5.90,
              8.00,
              10.30,
              -3.83,
              -2.12,
              0.47,
              2.92,
              5.07,
              7.25,
              9.57),
       height = c(1.60,
              3.40,
              5.40,
              7.40,
              9.30,
              11.00,
              12.60,
              1.60,
              3.10,
              4.60,
              6.30,
              7.80,
              9.30,
              10.70,
              NA,
              2.10,
              3.70,
              5.40,
              7.10,
              8.60,
              10.10,
              2.30,
              5.00,
              7.60,
              10.10,
              12.30,
              14.30,
              16.10,
              NA,
              2.20,
              5.20,
              8.40,
              11.40,
              14.10,
              16.50,
              NA,
              1.90,
              3.70,
              5.80,
              8.00,
              10.10,
              12.10,
              1.83,
              2.95,
              5.03,
              7.23,
              9.32,
              11.23,
              13.02),
       species = c("BE",
       "BE",
       "BE",
       "BE",
       "BE",
       "BE",
       "BE",
       "OA",
       "OA",
       "OA",
       "OA",
       "OA",
       "OA",
       "OA",
       "SP",
       "SP",
       "SP",
       "SP",
       "SP",
       "SP",
       "SP",
       "JL",
       "JL",
       "JL",
       "JL",
       "JL",
       "JL",
       "JL",
       "DG",
       "DG",
       "DG",
       "DG",
       "DG",
       "DG",
       "DG",
       "NS",
       "NS",
       "NS",
       "NS",
       "NS",
       "NS",
       "NS",
       "all",
       "all",
       "all",
       "all",
       "all",
       "all",
       "all"))

# Get linear model statistics
regression_data <- maxvegdat %>% 
  group_by(species) %>% 
  summarise(x = max(min),
            y = max(height),
            intercept = coef(lm(height ~ diameter))[1], 
            slope = coef(lm(height ~ diameter))[2])

# Create scatter plot of relation height and diameter at breast height
ggplot(data = maxvegdat, aes(x = diameter, y = height, color = species))+
  geom_point()+
  geom_hline(yintercept = 0)+
  geom_vline(xintercept = 0)+
  stat_smooth(method = "lm",
              se = F) +
  theme_minimal() +
  ggtitle("Relation tree height and diameter") +
  xlab("diameter (cm)") +
  ylab("height (m)") +
  theme(plot.title = element_text(size = 12,
                                  face = "bold",
                                  hjust = 0.5))

  
## Maximum vegetation growth

# Get data for each tree species
maxveggrowth <- tibble(height = c(1.60,
                                  3.40,
                                  5.40,
                                  7.40,
                                  9.30,
                                  11.00,
                                  12.60,
                                  1.60,
                                  3.10,
                                  4.60,
                                  6.30,
                                  7.80,
                                  9.30,
                                  10.70,
                                  NA,
                                  2.10,
                                  3.70,
                                  5.40,
                                  7.10,
                                  8.60,
                                  10.10,
                                  2.30,
                                  5.00,
                                  7.60,
                                  10.10,
                                  12.30,
                                  14.30,
                                  16.10,
                                  NA,
                                  2.20,
                                  5.20,
                                  8.40,
                                  11.40,
                                  14.10,
                                  16.50,
                                  NA,
                                  1.90,
                                  3.70,
                                  5.80,
                                  8.00,
                                  10.10,
                                  12.10,
                                  1.83,
                                  2.95,
                                  5.03,
                                  7.23,
                                  9.32,
                                  11.23,
                                  13.02),
                       age = c(5,
                               10,
                               15,
                               20,
                               25,
                               30,
                               35,
                               5,
                               10,
                               15,
                               20,
                               25,
                               30,
                               35,
                               5,
                               10,
                               15,
                               20,
                               25,
                               30,
                               35,
                               5,
                               10,
                               15,
                               20,
                               25,
                               30,
                               35,
                               5,
                               10,
                               15,
                               20,
                               25,
                               30,
                               35,
                               5,
                               10,
                               15,
                               20,
                               25,
                               30,
                               35,
                               5,
                               10,
                               15,
                               20,
                               25,
                               30,
                               35),
                       species = c("BE",
                                   "BE",
                                   "BE",
                                   "BE",
                                   "BE",
                                   "BE",
                                   "BE",
                                   "OA",
                                   "OA",
                                   "OA",
                                   "OA",
                                   "OA",
                                   "OA",
                                   "OA",
                                   "SP",
                                   "SP",
                                   "SP",
                                   "SP",
                                   "SP",
                                   "SP",
                                   "SP",
                                   "JL",
                                   "JL",
                                   "JL",
                                   "JL",
                                   "JL",
                                   "JL",
                                   "JL",
                                   "DG",
                                   "DG",
                                   "DG",
                                   "DG",
                                   "DG",
                                   "DG",
                                   "DG",
                                   "NS",
                                   "NS",
                                   "NS",
                                   "NS",
                                   "NS",
                                   "NS",
                                   "NS",
                                   "all",
                                   "all",
                                   "all",
                                   "all",
                                   "all",
                                   "all",
                                   "all"))

# Get linear model statistics
regression_data_growth <- maxveggrowth %>% 
  group_by(species) %>% 
  summarise(intercept = coef(lm(height ~ age))[1], 
            slope = coef(lm(height ~ age))[2]) %>% 
  mutate(speed_3_years = slope*3)

# Create scatter plot of relation height and age
ggplot(data = maxveggrowth, aes(x = age, y = height, color = species))+
  geom_point()+
  geom_hline(yintercept = 0)+
  geom_vline(xintercept = 0)+
  stat_smooth(method = "lm",
              se = F) +
  theme_minimal() +
  ggtitle("Relation tree height and age") +
  xlab("age (y)") +
  ylab("height (m)") +
  theme(plot.title = element_text(size = 12,
                                  face = "bold",
                                  hjust = 0.5))
